### PR TITLE
Add Spanish translations

### PR DESCRIPTION
**Pull request by eatyourgreens**
Depends on adding Russian and Czech translations to Zooniverse/zooniverse-readymade

### CODE REVIEW

**Comment by eatyourgreens** [comment]
Shouldn't merge this until readymade is updated, but wouldn't mind your thoughts on this @chrissnyder

**Comment by chrissnyder** [comment]
Something wrong with how the nav bar is being translated:

https://i.imgur.com/XKkrhem.png

Also, have you had any luck pushing new versions of the language file to translations.zooniverse.org? I remember running into difficulty there but I forget what the exact problem was.

**Comment by eatyourgreens** [comment]
Looks like you've got an old version of readymade there. I changed the pages object in 0.8.0 to allow for translation of page titles.

Spanish looks ok on www.penguinwatch.org/beta but readymade is missing some Russian and Czech language strings. At the moment, I think the only way to add translations to readymade is to issue PRs for its language files.

**Comment by chrissnyder** [comment]
Oops, yep, updating readymade fixed that.

LGTM. And yes, you are correct that the only current way to add translations to readymade is by adding a language file to https://github.com/zooniverse/zooniverse-readymade/tree/master/src/translations

**Comment by chrissnyder** [comment]
Should I merge this or wait until we add Russian/Czech to readymade?

**Comment by yshish** [comment]
Russian should be done for 100%, is there anything missing? 
I'm working on Czech these days. Hopefully will be ready on Sunday.

**Comment by chrissnyder** [comment]
In PW itself, yep, and 100% thanks for that!

What Jim is referring to is the common text that is used on all projects that use this tech. The en-us file is located here https://github.com/zooniverse/zooniverse-readymade/blob/master/src/translations/en.coffee and copy-pasted below:

```
module.exports =
  home: 'Home'
  classify: 'Classify'
  profile: 'Profile'
  science: 'Science'
  team: 'Team'

  getStarted: 'Get started!'
  thankYou: 'Thank you. Your classification has been recorded.'
  yes: 'Yes'
  no: 'No'
  talkQuestion: 'Do you want to talk about this image?'
  existingComments: 'There are already <span class="readymade-existing-comments-count">&mdash;</span> comments.'
  share: 'Share this image:'
  next: 'Next'
  previous: 'Previous'
  finished: 'Finished'
  back: 'Back'

  favorite: 'Favorite'
  favoriteIcon: '<i class="fa fa-heart-o readymade-clickable-not-checked"></i>'
  favoriteIconChecked: '<i class="fa fa-heart readymade-clickable-checked" style="color: orangered;"></i>'
  hideOldMarks: 'Hide old marks'
  hideOldMarksIcon: '<i class="fa fa-eye-slash readymade-clickable-not-checked"></i>'
  hideOldMarksIconChecked: '<i class="fa fa-eye-slash readymade-clickable-checked" style="color: orangered;"></i>'
  restartTutorial: 'Restart tutorial'
  tutorialIcon: '<i class="fa fa-graduation-cap"></i>'
```

I feel like we've asked people to translate this a bunch, some of which is available at https://github.com/zooniverse/Zooniverse/tree/master/src/translations.

**Comment by eatyourgreens** [comment]
@yshish @chrissnyder I've started a russian-czech branch of readymade. Translations can be added in the files here: https://github.com/zooniverse/zooniverse-readymade/tree/russian-czech/src/translations

**Comment by yshish** [comment]
Thanks for exaplaning. I'm still a bit confused.. 
 >home: 'Нome'
  classify: 'Classify'
  profile: 'Profile'
  science: 'Výzkum'
  team: 'Team'
etc.

Some of them are translated, some are not. Is there any reason they are not included in the translation page for PW? Translators don't know there are some more texts elsewhere to be translated.

How am I supposed to send you the translation of these lines / What is the best way for you?
I can send them to the PW Russian guy too. Not sure he's still an active user though.

Thanks!

**Comment by eatyourgreens** [comment]
@yshish these are the common language files that are shared across Penguin Watch, Science Gossip and a couple of other projects.

You can email the translations to me, if that's easiest for you?

Jim

**Comment by yshish** [comment]
Well, some of them have been translated for the PP already, so I was confused why that couldn't be used across the other projects. Never mind, I'm sending you the translation via email :)

**Comment by eatyourgreens** [comment]
Readymade 0.8.3 has Czech (thanks @yshish!) and I've commented out the Russian menu option. Deployed to penguinwatch.org/beta for checking. Should be good to merge now.

**Comment by chrissnyder** [comment]
The science page isn't translating, despite the text being available in the translations interface. Other than that I *think* it translates everything correctly.

**Comment by eatyourgreens** [comment]
@chrissnyder weird. I just deployed from translations.zooniverse.org again, but http://www.penguinwatch.org/beta/translations/cs.json still has the science text in English.

Spanish science page is fine, so I think this is a bug in the language file.

**Comment by yshish** [comment]
And it is not displaying any of the corrections I made a few days ago either (not sure whether it should display them).

**Comment by eatyourgreens** [comment]
My fault. I didn't set the headers properly when I copied that file to S3, so it's showing an out-of-date version. I just downloaded the json file and it looks fine.

**Comment by eatyourgreens** [comment]
@yshish I think it's fixed now if you clear the browser cache to get rid of the old translations.

**Comment by yshish** [comment]
@eatyourgreens It didn't help. Still seeing "DISKUTOVAT" instead of TALK on the top menu.

**Comment by yshish** [comment]
Ah, now it is working! After going through the Tutorial, it has changed for TALK.  :+1:

**Comment by eatyourgreens** [comment]
@yshish cool, sounds like a caching issue. Here's what I see
image

**Comment by yshish** [comment]
Ej, there is something wrong. The Naše vize is twice there. Like two different versions in a single text field. It is wrong in the Translation page. Ej. It needs more work than I thought :( I will fix it tonight/tomorrow. Promise.

**Comment by eatyourgreens** [comment]
There's just a little bit of HTML accidentally repeated at the beginning of that section. I deleted it, but I get a 'forbidden' error on the translations site when I try to save the new text.

**Comment by chrissnyder** [comment]
@eatyourgreens I think that was because your account wasn't identified as a translator for PW. I've added you, so you should be able to edit the text now.

**Comment by eatyourgreens** [comment]
I've fixed some HTML errors in the science page, and deployed again from the translations page, but http://www.penguinwatch.org/?lang=./translations/cs.json#/science still shows errors for me.

The json file looks okay when I download it from S3. Could this be a problem with CloudFront caching the file?

**Comment by yshish** [comment]
I tried to deploy via private window and it displays correctly! http://www.penguinwatch.org/?lang=./translations/a98c1df4341cee1e.json#/science (not sure what S3 etc, means)

**Comment by eatyourgreens** [comment]
Cool. I think we are good to merge this and deploy to production?

**Comment by chrissnyder** [comment]
:shipit:

**Comment by yshish** [comment]
Just checking the Czech version. Look at the http://www.penguinwatch.org/#/team The headings there are not available on the Translation page, and so haven't been translated:

Organizations = Organizace
Scientists = Tým vědeckých pracovníků
Developers = Tým vývojářů

The other problem is classifying Other animals - the pop-up menu appears completely in English. Could you look at it please? Thanks!

**Comment by eatyourgreens** [comment]
I've added translatable titles to the team page in #78 

I'm afraid I'm not sure what's going on with the 'Other animals' menu.

**Comment by yshish** [comment]
Should it be working now? I still see them in English (using private win, cleared browser cache)

**Comment by chrissnyder** [comment]
"Other animals" now works. Not yet on team page.

**Comment by yshish** [comment]
Still seeing Other animals in English.

**Comment by yshish** [comment]
The *Other animals* pop-up finally appears in Czech. There's just one line in English, the heading *"What is this?"* = *"Co je to?"*. Please, put it there instead of the English one. Thanks.

(Then the headings on Team page, but you said they shouldn't be displaying in Czech yet.)

**Comment by eatyourgreens** [comment]
The 'What is this?' question should be fixed by 1d800162964bdec62c72493d4e97d8c10dc8be84

The new text needs to be added to the translations page, but I'm getting an error when I try to push new translations, so I think I need @chrissnyder to help me there.

**Pull request merged**
